// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncdugyoaxofhpydntmwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZHVneW9heG9maHB5ZG50bXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODY2NDEsImV4cCI6MjA2MjQ2MjY0MX0.1V1F8cLVr7-7Vfx8SCpGcJdxcfjWVo3byURvGMAn7-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);