
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgxmuqvwwkxugvyspcwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRneG11cXZ3d2t4dWd2eXNwY3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjA1MDUsImV4cCI6MjA2MDgzNjUwNX0.dImvfAModlvq8rqduR_5FOy-K4vDF22ko_uy6OiRc-0";

// Public client configuration with explicit auth settings for reliability
const supabaseOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'viva_auth_token',
    flowType: 'pkce' as const,
  }
};

// Export the supabase client with correct types and options
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);

// Helper function to get the correct site URL for redirects
export const getSiteUrl = () => {
  // Production detection - add more domains as needed
  const isProd = window.location.hostname === 'vivaesportes.com.br';
  const productionUrl = 'https://vivaesportes.com.br';
  
  // Development or preview URL
  const developmentUrl = window.location.origin;
  
  console.log("Environment detection:", { isProd, url: isProd ? productionUrl : developmentUrl });
  return isProd ? productionUrl : developmentUrl;
};

// Get login redirect options - used for auth providers that require redirects
export const getLoginRedirectOptions = () => {
  const baseUrl = getSiteUrl();
  return {
    redirectTo: `${baseUrl}/login`,
  };
};

// Check if Supabase is properly configured - fix type checking logic
export function isSupabaseConfigured() {
  return Boolean(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY);
}
